# This is a basic workflow to help you get started with Actions

name: "build kernels"

# Controls when the workflow will run
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: "install prerequisites"
        run: |
          sudo apt-get install git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "checkout repo"
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: "fetch source"
        run: |
          cd ..
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.14.tar.xz
          tar Jxf linux-6.14.tar.xz
          cd linux-6.14
          cp ../kernel_build/conf/config ./.config

      - name: "build kernel"
        run: |
          make -j$(nproc)

